### ISSUE TITLE
dt vraiment utile ?

### ISSUE THREAD

**Issue by skyf0l** [TempoDev/Arcade-Toulouse#12]
Est-ce-que dt est vraiment utile dans les fonctions `void update(Scene &scene, float dt)` du game et graphic ?
Ca ne serait pas plus simple de gérer directement le fps dans la game loop ?

**Comment by nasso** [comment]
Oui, absolument, [sauf pour la physique](https://gafferongames.com/post/fix_your_timestep/). Mais c'est quelque chose qui pourra être géré par le jeu si il en a besoin. Le mieux que l'ont puisse faire c'est de fournir un delta d'une manière ou d'une autre.

**Comment by TempoDev** [comment]
Je ne pense pas que ce soit aux lib de gérer delta time, il faudrait qu'on le recode à chaques fois dans toutes les libs, alors qu'on peut le coder une fois dans le core et le fournir.

**Comment by nasso** [comment]
> Je ne pense pas que ce soit aux lib de gérer delta time, il faudrait qu'on le recode à chaques fois dans toutes les libs, alors qu'on peut le coder une fois dans le core et le fournir.

Oui totalement, je voulais dire le jeu pourra gérer son propre "fixed update" à partir du delta que le core lui fourni.

**Comment by TempoDev** [comment]
ok, sujet clos donc
