### ISSUE TITLE
Créer classe Sprite

### ISSUE THREAD

**Issue by TempoDev** [TempoDev/Arcade-Toulouse#26]
Créer l'interface `ISprite`, qui hérite de IComponent.
Elle permet d'afficher un sprite représenté sous la forme d'un tableau de pixels colorés.
LIB GRAPHIC ONLY !

**Comment by nasso** [comment]
> LIB GRAPHIC ONLY

C'est à dire?

**Comment by TempoDev** [comment]
Bah créer l'interface qui implémente un composant sprite : https://github.com/TempoDev/Arcade-Toulouse/discussions/10
Il faudra surement créer une fonction `ISprite *createSprite()` qui crée un sprite pour les jeux.

**Comment by TempoDev** [comment]
voir mise à jour et débat : https://github.com/TempoDev/Arcade-Toulouse/discussions/36

**Comment by TempoDev** [comment]
https://github.com/TempoDev/Arcade-Toulouse/commit/5a83c6f53dc2bc936b85d13adb05fb474bf8bbba
