### ISSUE TITLE
Créer IText

### ISSUE THREAD

**Issue by TempoDev** [TempoDev/Arcade-Toulouse#27]
Créer l'interface `IText`, qui hérite de IComponent.
Elle permet d'afficher un texte représenté sous la forme d'une string.

**Comment by nasso** [comment]
Je suis pas sûr que ça soit nécessaire. Ça rajoute du boulot au core alors qu'au final le jeu peut afficher du texte avec des sprites (graphiques ou ASCII). Ça lui permet aussi de définir une police de caractère personnalisée.

**Comment by TempoDev** [comment]
Heu... je vois pas comment tu veux afficher du texte avec des sprites graphiques, ou plutôt je vois mais je ne me vois pas créer 36 sprites juste pour afficher les caractères de base et je ne sais combien d'entitées pour les afficher.
Y a des limites quand même et ce serait beaucoup plus simple de créer un composant texte qui affiche du texte, c'est pas la mort non plus (surtout qu'il faut afficher les scores etc, c'est normal de vouloir du texte et non pas des images).

**Comment by nasso** [comment]
Ça apporte beaucoup trop de complexité au core justement:

- Quelle police utiliser?
- Quelle taille?
- Quelle variante de la police?
- Que faire si la police n'est pas disponible?
- Que faire de la police si on est en textuel (ncurses)?
- Que faire de la taille du texte si on est en textuel (ncurses), la ou sa taille ne peut pas être changée?
- Comment faire pour centrer le texte (ou calculer sa taille si besoin)?

C'est pour toutes ces raisons que 100% des jeux vidéos aujourd'hui se débrouillent avec des sprites pour "afficher du texte". Ils ont un contrôle total sur son alignement et son affichage, et la librairie graphique/core/moteur reste simple.

**Comment by TempoDev** [comment]
Quelle police utiliser? : la lib graphic gère
    Quelle taille? : la lib graphic gère OU définissable dans l'interface (dans ce cas graphic only)
    Quelle variante de la police? : non
    Que faire si la police n'est pas disponible? : au choix, message d'erreur, arrêt du programme, c'est au choix du core/lib graphique
    Que faire de la police si on est en textuel (ncurses)? : ça change rien, c'est du texte
    Que faire de la taille du texte si on est en textuel (ncurses), la ou sa taille ne peut pas être changée? : graphic only
    Comment faire pour centrer le texte (ou calculer sa taille si besoin)? : Méthodes de l'interface, pour le reste c'est pareil avec un sprite voir pire.

**Comment by TempoDev** [comment]
https://github.com/TempoDev/Arcade-Toulouse/commit/5a83c6f53dc2bc936b85d13adb05fb474bf8bbba
