### ISSUE TITLE
Débat Arcade

### ISSUE THREAD

**Issue by TempoDev** [TempoDev/Arcade-Toulouse#3]
Bonjour, il faut travailler sur quoi faire et comment améliorer les interfaces de l'arcade.
Il faut définir ce que contient scène et comment intéragir entre le jeu, le core et la librairie graphique.

Merci de participer et de donner vos avis ou de préciser ce que vous ne comprenez pas, sinon on fera l'archi sans vous tant pis pour vous.

**Premierement, la lib game interagie avec une scene, il serait bon de définir ce que l'on peut trouver dans cette classe.**

**Comment by fenikssc** [comment]
Dans la scène je viendrais mettre un ensemble d'entités, donc ajouter les méthodes addEntity, getEntity
Ça viendrait à créer une autre classe Entity qui contiendrait ce dont une entité a besoin hp, position etc..

**Comment by TempoDev** [comment]
Oui, je propose d'ajouter un attribut `m_entities` dans la scène :

```cpp
std::unordered_map<std::string, arcade::entity> m_entities;
```

Ainsi que les méthodes : 
```cpp
arcade::Entity &getEntity(std::string name);
std::unordered_map<std::string, arcade::entity> &getEntities();
void addEntity(arcade::Entity &entity);
void removeEntity(std::string name);
```

et donc une classe `class Entity`.

**Comment by nasso** [comment]
Je pense qu'`Entity` devrait plutôt être une interface afin de donner le plus de libertés à l'implémentation:

```cpp
class IEntity {
public:
    virtual ~IEntity() = default;
    
    virtual void addComponent(const std::string& name, void* data) = 0;
    virtual bool hasComponent(const std::string& name) const = 0;
    virtual void* getComponent(const std::string& name) = 0;
};
```
