### ISSUE TITLE
Gérer les events de la souris

### ISSUE THREAD

**Issue by TempoDev** [TempoDev/Arcade-Toulouse#31]
Créer une structure `MouseEvent` qui stock un évenement de la souris.
```cpp
struct MouseEvent {
    int x;
    int y;
    enum {
        MOUSE_PRIMARY,
        MOUSE_SECONDARY,
        MOUSE_AUXILIARY,
    } button;
};
```

**Comment by Jad31** [comment]
Faut-il mettre cette structure un mouse.hpp comme pour le keyboard.hpp ?

**Comment by TempoDev** [comment]
Heu ouaip.Je link la discussion au passage : https://github.com/TempoDev/Arcade-Toulouse/discussions/10
