### ISSUE TITLE
Il n'y a pas de coding style explicite

### ISSUE THREAD

**Issue by nasso** [TempoDev/Arcade-Toulouse#38]
Actuellement les fichiers de ce repository ne suivent pas de style de code particulier. Afin de garantir un style commun et de permettre à tout le monde de plus facilement contribuer au projet, je propose de le rendre plus explicite, potentiellement via un fichier de configuration ou une documentation écrite.

**Comment by Arcahub** [comment]
#39  Solve this issue

**Comment by TempoDev** [comment]
Alors autant je comprend le désir d'avoir un truc propre pour le repo, autant faut pas s'attendre à ce que tout le monde le suive, les gens ont bien d'autres préoccupations que celle là honnêtement (genre avoir un code qui marche lol).
Mais Je vais merge parce que c'est automatique.
