### ISSUE TITLE
Savoir si une lib graphique est Ascii

### ISSUE THREAD

**Issue by TempoDev** [TempoDev/Arcade-Toulouse#4]
Bonjour,

que pensez vous d'avoir un moyen de savoir si une lib est graphique on non pour agir en conséquence ?

**Je propose l'ajour d'une méthode `bool isAscii() const` dans l'interface `IGraphic`.**

**Comment by NoOverflow** [comment]
Tu dois surtout pas faire de différentiation entre deux libs graphiques, une lib graphique c'est une lib graphique  c'est tout. Si tu commences à faire des special cases c'est la sauce et c'est contraire au sujet.

![image](https://user-images.githubusercontent.com/54811870/112016463-05add680-8b2d-11eb-9bca-8e5df66bc5f9.png)

**Comment by TempoDev** [comment]
oui enfin c'est très différent entre une lib graphique et une lib terminale, tu ne peux pas afficher des sprites sur terminal et ça fonctionne avec un système de x cases sur x cases qui affichent chacunes un charactère alors que la lib graphique peut avoir une infinité de couleurs, des images et fonctionne avec un système de pixels.

Je pense que c'est compliquer de faire un truc cool sans différencier les deux, pour avoir essayé lors du rush 3.
Certe tu pourrait utiliser la lib graphique pour simuler l'apparence d'un terminal mais bon, c'est dégueulasse.

**Comment by nasso** [comment]
Enfait c'est pas un problème si ça marche dans l'autre sens:
- Le jeu propose une version graphique et une version ASCII pour chacun de ses assets
- La lib graphique va aller chercher la version qui lui convient pour l'afficher
- Ni le core ni le jeu n'a besoin de savoir quelle version de l'asset à été utilisé par la librairie.

**Comment by TempoDev** [comment]
Ouais, on discutait tout à l'heure avec Ode et on se disait qu'un truc comme ça était mieux.

Mais dans ce cas là il faut définir ça dans les entités/components qui sont dans la scene, donc ça ramène au débat sur le contenu de la scène (https://github.com/TempoDev/Arcade-Toulouse/issues/3).

D'ailleurs je tiens à préciser que ce n'est pas que les assets, mais aussi les mouvements. Par exemple snake, il faudrait définir des cases en mode graphique et les mouvements seraient plus fluides et moins sacadés qu'en ascii ou c'est déjà case par case.

**Comment by nasso** [comment]
Pour les coordonnées ça peut être très simplement réglé en définissant une échelle différente du côté de la lib graphique (par exemple, `arcade_sdl.so` pourrait utiliser un zoom de 1/100 unité par pixel et `arcade_ncurses.so` 1/1 unité par pixel).

**Comment by TempoDev** [comment]
oui mais si tu fais ça, ton mouvement en graphic sera saccadé.

**Comment by nasso** [comment]
Les coordonnées sont des `float` (ou `double`) :p

**Comment by TempoDev** [comment]
Je vois le délire, ouais c'est pas con. Je sais pas si dans la pratique ça marche sans problèmes, mais je suis pour.

**Comment by NekoSelena** [comment]
Ça voudrait dire qu'on utliliserait ce qu'on a dit tout à l'heure Alexia ? Genre dans les entités on définit un `sprite_ascii` et un `sprite_png` *(par exemple, c'est histoire de comprendre)*, qui permettraient à la lib de savoir si elle doit afficher des caractères ascii ou bien un sprite, c'est ça ?

**Comment by TempoDev** [comment]
> Ça voudrait dire qu'on utliliserait ce qu'on a dit tout à l'heure Alexia ? Genre dans les entités on définit un `sprite_ascii` et un `sprite_png` _(par exemple, c'est histoire de comprendre)_, qui permettraient à la lib de savoir si elle doit afficher des caractères ascii ou bien un sprite, c'est ça ?

Oui en gros c'est ça.

**Comment by smbss1** [comment]
Ou bien, tu fais un ressource manager qui charge les ressources necessaire pour la lib graphique et un composant Render par exemple qui garde un ID vers la ressource dans le manager. Et le composant Render contient contient aussi un string qui est sa valeur en ascii pour les libs qui en auront besoin.
