### ISSUE TITLE
Problème sur IScene

### ISSUE THREAD

**Issue by max-ndj** [TempoDev/Arcade-Toulouse#47]
![image](https://user-images.githubusercontent.com/60672471/113292788-41972780-92f5-11eb-9d75-f41ca4037274.png)
Second problème, le paramètre de la méthode addEntity n'est pas bon : cela génère une erreur

**Comment by Ydos2** [comment]
Je ne vois pas en quoi le addEntity génère une erreur, tu voulais pas plutôt dire le pushEvent ?

**Comment by max-ndj** [comment]
Nan pushEvent ne pose pas de problème

**Comment by TempoDev** [comment]
je ne vois pas non plus comment addEntity peut poser problème et je vois aussi une erreur sur pushEvent mdr

**Comment by max-ndj** [comment]
Tu peux pas utiliser une interface en paramètre de cette manière, soit c'est une référence, soit c'est un unique_ptr, soit autre chose mais pas IEntity seul comme ça

**Comment by TempoDev** [comment]
Ha ouais, j'avais zappé mdr
faut mettre un `IEntity &&entity`,  utliser `std::move()`  (https://en.cppreference.com/w/cpp/utility/move)
ou constructeur par copie `const IEntity &entity` je pense ça passe vu que les comp sont des pointeurs.

**Comment by nasso** [comment]
Non ya un vrai problème aussi: `newEntity` retourne une référence: donc l'entité est stoquée ou?
