### ISSUE TITLE
Problème avec la méthode getEntity

### ISSUE THREAD

**Issue by max-ndj** [TempoDev/Arcade-Toulouse#49]
Quand je souhaite implémenter la méthode getEntity dans une classe concrète et que je compile, j'obtiens erreur
![image](https://user-images.githubusercontent.com/60672471/113338447-6907e780-9329-11eb-9197-1791f4bfc2d8.png)

J'en déduis que c'est à cause de la référence vers IEntity...

**Comment by TempoDev** [comment]
Tu peux montrer ta ligne de code où il y a l'erreur stp ?

**Comment by max-ndj** [comment]
![image](https://user-images.githubusercontent.com/60672471/113338945-1975eb80-932a-11eb-9af6-79c74f7a6a59.png)
En soit je n'ai fais que reprendre le prototype de la méthode (certes je ne return pas le vecteur donc ça ça me génère un warning, l'erreur ne vient pas de là)

**Comment by nasso** [comment]
Aah, je pense qu'il aime pas les vecteurs de référence (ce qui en soit est assez cursed de toute manière).

Au pire, go faire avec un simple `IEntity*` même si je trouve ça dommage.

**Comment by max-ndj** [comment]
Et pourquoi pas avec un unique_ptr ?

**Comment by Jad31** [comment]
Je crois qu'il y a le même problème avec les methods addComponent et removeComponent dans IEntity. On est d'accord qu'il faut un vecteur de IComponent également ? Maybe open une issue là dessus aussi ?

**Comment by max-ndj** [comment]
T'as une erreur en particulier avec les méthodes addComponent et removeComponent @Jad31 ?

**Comment by Jad31** [comment]
> T'as une erreur en particulier avec les méthodes addComponent et removeComponent @Jad31 ?

On a exactement le même problème que toi puisqu'on utilise des références vers IComponent

**Comment by TempoDev** [comment]
déso je suis pas sur l'arcade ce week end, j'ai des urgences.
En revanche c'est pas un problème les références, il suffit de les wraps :

```cpp
std::vector<reference_wrapper<int> > hello;
```
See : https://en.cppreference.com/w/cpp/utility/functional/reference_wrapper

Si quelqu'un s'en charge et fait une pull request je pense que @Ydos2  voudra bien la merge.

**Comment by Jad31** [comment]
J'en ai discuté avec Jerome, mais il vaut mieux partir sur un `reference_wrapper` en effet.

**Comment by max-ndj** [comment]
Je viens de faire la pull request pour ça

**Comment by Ydos2** [comment]
C'est bon pour le merge
