### ISSUE TITLE
Format des métadonnées

### ISSUE THREAD

**Issue by TempoDev** [TempoDev/Arcade-Toulouse#5]
La méthode `char *library_get_data()` doit retourner des information sur la lib, le format doit être commun sinon il sera impossible de les interpréter entre arcade.
Je propose le format simple suivant :

```
[type] (GAME|GRAPHIC)
[name]
[date](mm/jj/aaaa)
[description]
[additional info]
```
exemples :

```
GAME
Pacman
03/25/2021
pacman is a game whith ghosts and cheeses.
```

```
GRAPHIC
SDL
```

```
GRAPHIC
SDL
03/25/2021
the SDL Library for arcade.
```

Seul les 2 premières lignes seraient obligatoire, le reste serait des informations addictionnelles facultatives, donc attention lors du parsing.

**Comment by nasso** [comment]
Pourquoi ne pas utiliser une structure qu'on partage plutôt que de construire puis parse un `char*`?

```c
#include <time.h>

struct library_info_t {
    enum { GAME, GRAPHIC } type;
    char name[32];
    time_t date;
    char desc[256];
};
```

Ça me paraît bien plus simple et enlève une bonne dose de travail de parsing inutile en soit

**Comment by huntears** [comment]
> 
> 
> Pourquoi ne pas utiliser une structure qu'on partage plutôt que de construire puis parse un `char*`?
> 
> ```c
> #include <time.h>
> 
> struct library_info_t {
>     enum { GAME, GRAPHIC } type;
>     char name[32];
>     time_t date;
>     char desc[256];
> };
> ```
> 
> Ça me paraît bien plus simple et enlève une bonne dose de travail de parsing inutile en soit

C'est pas avec les typedef qu'il faut utiliser les `_t` ?

**Comment by TempoDev** [comment]
> > Pourquoi ne pas utiliser une structure qu'on partage plutôt que de construire puis parse un `char*`?
> > ```c
> > #include <time.h>
> > 
> > struct library_info_t {
> >     enum { GAME, GRAPHIC } type;
> >     char name[32];
> >     time_t date;
> >     char desc[256];
> > };
> > ```
> > 
> > 
> > Ça me paraît bien plus simple et enlève une bonne dose de travail de parsing inutile en soit
> 
> C'est pas avec les typedef qu'il faut utiliser les `_t` ?

```c
#include <time.h>

typedef struct library_info {
    enum { GAME, GRAPHIC } type;
    char name[32];
    time_t date;
    char desc[256];
} library_info_t;
```
voilà :p

**Comment by TempoDev** [comment]
Sinon je pense que c'est mieux comme ça aussi, je l'ajoute à api.h, si personne n'a d'objections à rajouter ?

**Comment by nasso** [comment]
Le seul "truc" sur lequel je suis pas sûr à 100% c'est pour les string, soit on opte pour un tableau de taille fixe maximale (ici 32 caractères max pour le nom et 256 max pour la description) soit on se dit que ça sera toujours des constantes et on peut alors se contenter d'un simple `const char*` qui serait alors de taille arbitraire (terminé par un `\0`).

**Comment by huntears** [comment]
> 
> 
> > > Pourquoi ne pas utiliser une structure qu'on partage plutôt que de construire puis parse un `char*`?
> > > ```c
> > > #include <time.h>
> > > 
> > > struct library_info_t {
> > >     enum { GAME, GRAPHIC } type;
> > >     char name[32];
> > >     time_t date;
> > >     char desc[256];
> > > };
> > > ```
> > > 
> > > 
> > > Ça me paraît bien plus simple et enlève une bonne dose de travail de parsing inutile en soit
> > 
> > 
> > C'est pas avec les typedef qu'il faut utiliser les `_t` ?
> 
> ```c
> #include <time.h>
> 
> typedef struct library_info {
>     enum { GAME, GRAPHIC } type;
>     char name[32];
>     time_t date;
>     char desc[256];
> } library_info_t;
> ```
> 
> voilà :p

Je pense qu'on peut encore l'améliorer, il y a un peu de padding qu'on peu utiliser, et avec l'aide du -Wpadded de clang j'ai finit sur ça : 
```c
#include <time.h>

typedef struct library_info {
    enum { GAME, GRAPHIC } type;
    char name[36];
    char desc[256];
    time_t date;
} library_info_t;
```

Et on gagne 4 bytes d'alignement :o

**Comment by nasso** [comment]
On est vraiment pas à ça près 😅

**Comment by NekoSelena** [comment]
J'ai pas vraiment compris à quoi servait cette structure... Elle permet de reconnaître si le .so est un game ou une library, c'est ça ? mais comment ça marche concrètement ? :disappointed:

**Comment by Trompettesib** [comment]
Si j'ai bien compris en gros elle permet de savoir à n'importe quel moment qu'es ce que tu va trouver dans ton .so en regardant les variables de ta struct

**Comment by NekoSelena** [comment]
Je crois que j'ai encore moins compris... :disappointed:

**Comment by TempoDev** [comment]
> J'ai pas vraiment compris à quoi servait cette structure... Elle permet de reconnaître si le .so est un game ou une library, c'est ça ? Mais comment ça marche concrètement ? disappointed

Dans ta librairie (ton .so) tu vas devoir définir **obligatoirement** 3 fonctions, définie dans api.h :

```c
void *library_create(); // crée une librarie que tu devras caster en IGraphic ou IGame selon si c'est un jeu ou une lib graphique
void library_delete(void *library); // free la librairie
char *library_get_data(); // donne toutes les informations nécessaires pour la lib, dont le type, le nom, etc...
```
ici, on parle de `char *library_get_data()` et plus précisément du format sous lequel on va récupérer ces informations.
On a finit par conclure de retourner les informations sous la forme d'une structure `library_info_t`.

Du coup la fonction changera comme suit : `char *library_get_data()` -> `library_info_t library_get_data()`

**Comment by NekoSelena** [comment]
Aaaaah... Donc `library_get_data()` va nous permettre de savoir si le .so est un game/une lib !

**Comment by TempoDev** [comment]
> Le seul "truc" sur lequel je suis pas sûr à 100% c'est pour les string, soit on opte pour un tableau de taille fixe maximale (ici 32 caractères max pour le nom et 256 max pour la description) soit on se dit que ça sera toujours des constantes et on peut alors se contenter d'un simple `const char*` qui serait alors de taille arbitraire (terminé par un `\0`).

bah techniquement ce sera forcément des constantes, genre c'est pas censé changer.

**Comment by nasso** [comment]
> Bah techniquement ce sera forcément des constantes, genre c'est pas censé changer.
> (en soit la structure elle-même est constante).

Alors on peut partir sur des `const char*` pour avoir une longueur illimité pour le nom et la description.

**Comment by TempoDev** [comment]
```c
#include <time.h>

typedef struct library_info {
    enum { GAME, GRAPHIC } type;
    char *name;
    time_t date;
    char *desc;
} library_info_t;
```

**Comment by NekoSelena** [comment]
Ça veut dire que si on veut les utiliser, il faudra les malloc ?

**Comment by TempoDev** [comment]
> Ça veut dire que si on veut les utiliser, il faudra les malloc ?

Non, tu n'as rien à malloc, c'est constant.

**Comment by NekoSelena** [comment]
Aaaah oui chuis con sorry
