### ISSUE TITLE
Problème avec le name dans IScene

### ISSUE THREAD

**Issue by Jad31** [TempoDev/Arcade-Toulouse#50]
Bonjour,

Les methods `removeEntity` et `getEntity` prennent un `std::string name` en argument et return un vecteur de `IEntity`.
**Du coup**, on ne peut pas accéder à `name`. Y'a-t-il un moyen d'y accéder ou faut-il créer une abstract avec un `getName()`?

**Comment by TempoDev** [comment]
Ton dois créer une classe entity qui hérite de IEntity, ton core sais que toutes les IEntity sont de Entity et à partir de la tu peux mettres ce que tu veux dedans, et donc un nom, que tu peux récupérer dans IScene (ou plutot scene).

En ce qui concerne ajouter un getName() a IEntity avait effectivement été demandé mais je crois qu'on a oublié de l'ajouter, meême si elle n'est pas indispensable

**Comment by Jad31** [comment]
J'ai déjà ma classe `Entity` que j'ai essayer de récupérer depuis `Scene` mais je ne voyais pas comment faire.
Finalement, en plus de mon vector, je vais utiliser une `unordered_map` avec comme clé le name, et comme value l'IEntity. Je n'aurai plus qu'à comparer avec le `name` donné en paramètre dans le methods pour les ajouter dans mon vector :)

**Comment by nasso** [comment]
Fais gaffe, il n'est écrit nulle part que le nom est un identifiant unique :)

**Comment by Jad31** [comment]
Et comment on fait pour les entity qui n'ont pas de name également ?

**Comment by nasso** [comment]
Il n'est juste pas possible de les récupérer avec `getEntity(const std::string& name)`

**Comment by Jad31** [comment]
Quel est l'intérêt d'avoir des Entity sans nom et d'avoir un `newEntity()` qui ne prend pas de paramètres ?

**Comment by nasso** [comment]
> Quel est l'intérêt d'avoir des Entity sans nom

Toutes les entités n'ont pas besoin de nom: par exemple dans un jeu snake, les entités qui composent le corps de ton serpent n'ont pas besoin d'être toutes individuellement nommées. De même pour les points dans un pacman.

> d'avoir un newEntity() qui ne prend pas de paramètres ?

Pour créer une entité sans-nom!

> Et est-ce que plusieurs Entity peuvent avoir le même nom ?

Oui totalement.

**Comment by TempoDev** [comment]
Parce que nasso refusait totalement d'avoir des noms dans ses entitées et on en a eu marre qu'il nous harcèle du coup on lui a mis ses fonctions qu'il voulait **absolument**.

**Comment by nasso** [comment]
OUI!

**Comment by Ydos2** [comment]
S'il n'y a plus de questions au par rapport au nom dans le IScene, je ferme l'issues ce soir.
