### ISSUE TITLE
Problème avec std::find pour chercher une IEntity

### ISSUE THREAD

**Issue by smbss1** [TempoDev/Arcade-Toulouse#61]
J'ai ce genre de problème qui est afficher à la compilation: "   required from ‘_IIter std::find(_IIter, _IIter, const _Tp&) [with _IIter = __gnu_cxx::__normal_iterator<arcade::IEntity*, std::vector<arcade::IEntity> >; _Tp = arcade::IEntity]’" .

Du coup, je propose que l'on rajoute un 'GetId' dans IEntity pour avoir l'index de l'entity dans le container.

**Comment by nasso** [comment]
Il faut définir un comparateur pour que `std::find` puisse identifier ton entité. Pas besoin de `GetId` ou quoi, tout le monde n'a pas forcément ce mécanisme (e.g. les entités pourraient être contenues dans un `std::unordered_set`, auquel cas il n'y aura pas "d'indice").

**Comment by smbss1** [comment]
d'acc je vais m'informer un peu plus la dessus
