### ISSUE TITLE
Taille de l'écran

### ISSUE THREAD

**Issue by Ydos2** [TempoDev/Arcade-Toulouse#67]
Je propose une fonction dans scène pour changer la taille de l'écran.

```virtual void setWindowSize(int x, int y) = 0;```

**Comment by max-ndj** [comment]
Je vois pas forcément l'utilité mais d'un point de vue "propreté", pourquoi pas

**Comment by Ydos2** [comment]
C'est surtout pour supporter les différentes tailles d'écran dans la promo

**Comment by max-ndj** [comment]
Ah oui de ce point de vue là, pourquoi pas aussi

**Comment by Ydos2** [comment]
Bah, on reste dans le principe de compatibilité graphique.
Si quelqu'un est contre qu'on le rajoute, il faut en parler avant demain matin, je pense.

**Comment by Jad31** [comment]
Cette fonction peut aussi servir si l'utilisateur veux changer la taille de l'écran, même si ça serait assez chiant à mettre en place.

**Comment by nasso** [comment]
Il faut aussi une méthode côté `IGraphic` pour pouvoir vraiment changer la taille de la fenêtre. Où alors un `getWindowSize` pour que le `IGraphic` récupère la taille pour s'update lui même.

**Première option:**
```cpp
class IGraphic {
    // ...

    virtual void setWindowSize(int width, int height) = 0;

    // ...
};
```

**Seconde option:**
```cpp
class IScene {
    // ...

    virtual void setWindowSize(int x, int y) = 0;
    virtual Vector2 getWindowSize() const = 0;

    // ...
};
```

**Comment by Ydos2** [comment]
Je suis plusieurs partisan de la seconde option perso mais comme vous voulez.

**Comment by Ydos2** [comment]
Le changement vers la version 2 a était appliquer.
J'ai aussi rajouté un Vector2 pour le getWindowSize.
