### ISSUE TITLE
Paramètre de la méthode addComponent dans IEntity

### ISSUE THREAD

**Issue by max-ndj** [TempoDev/Arcade-Toulouse#72]
Il y a un souci avec le paramètre de addComponent, est-ce qu'il devrait être en const ?

**Comment by nasso** [comment]
Enfait il faut dynamic_cast pour faire une copie de l'event :)

**Comment by Jad31** [comment]
> Enfait il faut dynamic_cast pour faire une copie de l'event :)

On peut dynamic_cast une variable const ?

**Comment by nasso** [comment]
Oui on peut totalement, ça va juste te donner un `const IComponent*`
